name: 'Local Setup Node.js'
description: 'Check Node.js version (assumes Node.js is pre-installed)'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check Node.js version
      run: |
        echo "Node.js version on runner:"
        node --version
        echo "NPM version on runner:"
        npm --version
      shell: bash
