name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Cleanup workspace
        run: |
          rm -rf dist node_modules

      - name: Check Node.js version
        run: |
          echo "Node.js version on runner:"
          node --version
          echo "NPM version on runner:"
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist --base-href=/portfolio/

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cd ./dist
          git init
          git checkout --orphan gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
